### PR TITLE
Bump libwebp for Apple platform min deployment target version, to fix the Xcode 12 error

### PR DESCRIPTION
**Pull request by dreampiggy**
This fix https://github.com/SDWebImage/SDWebImageWebPCoder/pull/43

### CODE REVIEW

**Comment by mmdumi** [comment]
Can somebody merge this PR please, as it blocks the compile of SDWebImageWebPCoder for Xcode 12 with Carthage ?

**Comment by dreampiggy** [comment]
This...Depends on Google's libwebp official timeline: https://github.com/webmproject/libwebp/releases
If they don't release a new version (1.2.1), I can not release a new version as well :(

**Comment by mmdumi** [comment]
@dreampiggy Looks like there is a new release 1.2.0 with xcframework support.
Can we now finalise this please ? 
Thank you

**Comment by dreampiggy** [comment]
> @dreampiggy Looks like there is a new release 1.2.0 with xcframework support.
> Can we now finalise this please ?
> Thank you

I'll do it today.

**Comment by dreampiggy** [comment]
The macOS deployment target version should bump to 10.10+ as well.

**Pull request merged**
